[package]
name = "solanacomic"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solanacomic"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = { version="0.26.0", features = [ "metadata" ] }
mpl-bubblegum = { version="0.7.0", features = ["cpi"] }
mpl-token-metadata = { version="1.2.5", features = [ "no-entrypoint" ] }
spl-account-compression = { version="0.1.8", features = ["cpi"] }
solana-program = "1.15.2"
