[features]
seeds = false
skip-lint = false

[programs.localnet]
solanacomic = "3jtph9795JxAkC47KukHYuR7hPsBN5ou3eb2uC77Px6Z"

[programs.devnet]
solanacomic = "3jtph9795JxAkC47KukHYuR7hPsBN5ou3eb2uC77Px6Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# cluster = "Localnet"
wallet = "/Users/viandwi24/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
program = "./genesis/mpl_bubblegum.so"
